### PR TITLE
Use continuation-local-storage to save request id

### PR DESCRIPTION
**Pull request by thejollyrogers**
- add a transform function to bristol, to add the request id
to every meta data element for every log line

### CODE REVIEW

**Comment by nullstyle** [comment]
I feel like we should put `getNamespace()` behind a helper function.  Could we do something like the following sample work?

`stex.cls().get("requestId")`

**Comment by nullstyle** [comment]
:+1:

**Comment by bartekn** [comment]
:+1: 
One question: Let's say a developer wants to create a new namespace for his/her app (app is using stex). What happens when he creates a new namespace and bind it to the `req` and `res` (these are the same objects as in stex). Will it work? Maybe we should open it and allow devs to use this API?

**Comment by thejollyrogers** [comment]
@nullstyle pulled in core cls stuff into cls.js
@bartekn i've added a config value so that apps can provide their own namespace name

**Comment by nullstyle** [comment]
:+1:

**Pull request merged**
